export type ExperienceSection = {
	heading: string
	items: string[]
}

export type Experience = {
	slug: string
	year: string
	role: string
	company: string
	description: string
	tech: string[]
	dateRange?: string
	location?: string
	link?: { label: string; url: string }
	sections?: ExperienceSection[]
}

export const experiences: Experience[] = [
	{
		slug: 'gofoton',
		year: '2025',
		role: 'AI-Driven Business Development Lead',
		company: 'Go!Foton',
		description:
			'Own the Go!Foton Service Platform end-to-end — production reliability, integrations, CI/CD, and release management across project management, finance, workforce, compliance, and marketplace features. Serve as the technical bridge between engineering and executive leadership, translating architecture, infrastructure investments, and technical-debt trade-offs into business impact. Drive an accelerated innovation culture through structured prototyping, feature-flag-gated experiments, competitive intelligence, and emerging-technology assessments.',
		tech: ['Next.js', 'PostgreSQL', 'Azure', 'CI/CD', 'AI Strategy'],
		dateRange: '2025 — Present',
		location: 'Somerset, NJ',
		link: { label: 'gofoton.com', url: 'https://gofoton.com' },
		sections: [
			{
				heading: 'Platform Ownership',
				items: [
					'Own end-to-end production stability across app, database, authentication, and cloud infrastructure',
					'Maintain and extend integrations with PM tools, analytics, communications, background-check providers, and ERP systems',
					'Operate CI/CD with three-job validation (code quality, tests, build verification) and branch-protected staging/main environments',
					'Coordinate releases to limit disruption, enable rollbacks, and align migrations with scalability goals',
					'Improve monitoring, alerting, incident response, and backup/disaster recovery to reduce downtime and protect against data loss',
				],
			},
			{
				heading: 'Technical-to-Executive Translation',
				items: [
					'Translate architecture, technical-debt implications, and infrastructure investments into business impact (cost, risk, revenue, positioning)',
					'Deliver executive-level briefings that turn complex topics into clear decisions with quantified trade-offs',
					'Convert sprint-level engineering output into strategic updates suitable for board, investor, and customer communications',
					'Provide rapid assessments on risks, vendors, competitive threats, and customer escalations',
				],
			},
			{
				heading: 'Strategic Technology Advisory',
				items: [
					'Advise on build/buy decisions, vendor selection, scaling strategy, and stack evolution grounded in ROI and total cost of ownership',
					'Assess emerging technologies for fit with Go!Foton’s operating model',
					'Represent Go!Foton’s technology in customer, partner, and industry settings',
				],
			},
			{
				heading: 'Innovation Strategy & Execution',
				items: [
					'Formalize a structured software innovation process to propose, evaluate, and prototype new ideas',
					'Identify high-impact opportunities from usage data, customer feedback, and competitive intelligence',
					'Run rapid prototypes via feature flags, isolated environments, and time-boxed experiments',
					'Build reusable assets (components, templates, tests, internal tools) that compound delivery speed across the platform',
				],
			},
			{
				heading: 'Cross-Functional Alignment',
				items: [
					'Translate field workflows into prioritized requirements so the platform reflects operational reality',
					'Set the cadence for executive-level technology reviews covering health metrics, milestones, risks, and resourcing',
					'Create documentation, architecture decision records, and onboarding materials to scale the engineering team',
				],
			},
		],
	},
	{
		slug: 'ropes-and-gray',
		year: '2025',
		role: 'Information Security Intern',
		company: 'Ropes & Gray LLP',
		description:
			"Monitored and analyzed SIEM alerts to identify threats, responded to security incidents, and researched Microsoft's Azure Network Security Perimeter to enhance protection for sensitive workloads.",
		tech: ['SIEM', 'Azure', 'Security', 'Risk Assessment'],
		dateRange: '2025',
		sections: [
			{
				heading: 'Security Operations & Incident Response',
				items: [
					"Reviewed security alerts and logs using the firm's SIEM platform and supporting tooling",
					'Responded to events and alerts generated by security technologies, managed security providers, and user-reported activity suggestive of a potential information security incident',
					'Supported day-to-day operational tasks and alerts assigned to the Information Security Team',
					'Promptly responded to end-user requests for assistance and proactively assessed potential items of risk and vulnerability in the network',
				],
			},
			{
				heading: 'Vulnerability & Vendor Risk Management',
				items: [
					"Assisted with coordinating and executing the firm's vulnerability management program, including pre-deployment risk and compliance assessments",
					"Supported the firm's vendor risk management program and coordinated third-party technical risk assessments and audit activity",
					'Participated in internal technical risk assessments and audits',
				],
			},
			{
				heading: 'Security Documentation & Governance',
				items: [
					'Produced and maintained information security documentation including policies, procedures, standards, guidelines, and architecture diagrams',
					'Promoted a culture of information security across business units',
					'Adhered to relevant policies, procedures, standards, and accepted security practices',
				],
			},
			{
				heading: 'Technology Evaluation & Cloud',
				items: [
					'Participated in the design, maintenance, and development of firm technology solutions',
					"Researched Microsoft's Azure Network Security Perimeter to strengthen protection of sensitive workloads",
					'Stayed current on emerging cloud technologies and evaluated vendor offerings to determine best fit for business needs',
				],
			},
		],
	},
	{
		slug: 'stevens-course-assistant',
		year: '2024',
		role: 'Course Assistant',
		company: 'Stevens Institute of Technology',
		description:
			'Created and presented instructional content on UI/UX design, git, deploying web apps, and domain management. Provided personalized support to help students resolve technical challenges.',
		tech: ['UI/UX', 'Git', 'Web Deployment', 'Teaching'],
		dateRange: '2024',
		location: 'Hoboken, NJ',
		sections: [
			{
				heading: 'Curriculum & Instruction',
				items: [
					'Designed and presented lessons on UI/UX design fundamentals, including layout, typography, and visual hierarchy',
					'Walked students through practical git workflows — branching, committing, resolving merge conflicts, and collaborating via pull requests',
					'Taught web app deployment using modern hosting platforms, covering build pipelines, environment configuration, and production rollouts',
					'Introduced domain management essentials: registrars, DNS records, name servers, and connecting custom domains to deployed sites',
				],
			},
			{
				heading: 'Student Support',
				items: [
					'Provided personalized one-on-one help during sessions and office hours to unblock students stuck on technical issues',
					'Debugged student code alongside them, modeling diagnostic thinking rather than just handing over solutions',
					'Clarified concepts in plain language for students newer to web development, meeting them at their own experience level',
				],
			},
		],
	},
	{
		slug: 'aventix',
		year: '2022',
		role: 'Co-Founder',
		company: 'Aventix',
		description:
			'Co-founded and developed a multi-platform application enabling users to manage events and purchase tickets using Web3 technology. Directed a team of three developers and designers, establishing clear objectives and achieving all project milestones.',
		tech: ['Next.js', 'React Native', 'Node.js', 'Supabase', 'Web3'],
		dateRange: '2022 — Present',
		link: { label: 'aventix.net', url: 'https://aventix.net' },
		sections: [
			{
				heading: 'Product Strategy & Vision',
				items: [
					'Co-founded Aventix and shaped the product vision around improving trust, security, and transparency in event ticketing',
					'Set technical direction across the web application, mobile apps, and backend services',
					'Established project objectives and milestones and delivered against them on schedule',
				],
			},
			{
				heading: 'Cross-Platform Engineering',
				items: [
					'Built the consumer-facing web application in Next.js',
					'Built the iOS and Android mobile apps in React Native, sharing logic across platforms',
					'Designed the Node.js + Supabase backend powering authentication, event management, and ticket inventory',
				],
			},
			{
				heading: 'Web3 Ticket Integrity',
				items: [
					'Integrated blockchain infrastructure to make tickets tamper-resistant and ownership verifiable end-to-end',
					'Built secure purchase, transfer, and validation flows leveraging Web3 to guarantee authenticity in every transaction',
				],
			},
			{
				heading: 'Team Direction',
				items: [
					'Directed a team of three developers and designers, establishing clear objectives and reviewing progress against milestones',
					'Coordinated design, engineering, and product priorities to ship cohesive features across web and mobile',
				],
			},
		],
	},
]

export function getExperienceBySlug(slug: string): Experience | undefined {
	return experiences.find((e) => e.slug === slug)
}
